# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures With Pixel
email: daddy@adventureswithpixel.com
description: > # this means to ignore newlines until "baseurl:"
  The adventures of a father, son, and trusty hound through the urban setting of Toronto. El&nbsp;Granto, Pixel, Kristen, and Odin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
