# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures With Pixel
email: daddy@adventureswithpixel.com
description: > # this means to ignore newlines until "baseurl:"
  The adventures of a father and son through the urban setting of Toronto Ontario. El Granto and Pixel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: El_Granto
github_username:  ElGranto

# Build settings
markdown: kramdown
